export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";
export const TOGGLE_ITEM_AVAILABILITY = "TOGGLE_ITEM_AVAILABILITY";
export const UPDATE_THEME = "UPDATE_THEME";
export const SELECT_ALL_ITEMS = "SELECT_ALL_ITEMS";
export const REMOVE_ALL_ITEMS = "REMOVE_ALL_ITEMS";
