export const FETCH_MENU_REQUEST = "FETCH_MENU_REQUEST";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_FAILURE = "FETCH_MENU_FAILURE";
export const TOGGLE_ITEM_AVAILABILITY = "TOGGLE_ITEM_AVAILABILITY";
export const UPDATE_THEME = "UPDATE_THEME";
export const SELECT_ALL_ITEMS = "SELECT_ALL_ITEMS";
export const REMOVE_ALL_ITEMS = "REMOVE_ALL_ITEMS";

export const SAVE_THEME_REQUEST = "SAVE_THEME_REQUEST";
export const SAVE_THEME_SUCCESS = "SAVE_THEME_SUCCESS";
export const SAVE_THEME_FAILURE = "SAVE_THEME_FAILURE";

export const CREATE_DISPLAY_REQUEST = "CREATE_DISPLAY_REQUEST";
export const CREATE_DISPLAY_SUCCESS = "CREATE_DISPLAY_SUCCESS";
export const CREATE_DISPLAY_FAILURE = "CREATE_DISPLAY_FAILURE";

export const DELETE_DISPLAY_REQUEST = "DELETE_DISPLAY_REQUEST";
export const DELETE_DISPLAY_SUCCESS = "DELETE_DISPLAY_SUCCESS";
export const DELETE_DISPLAY_FAILURE = "DELETE_DISPLAY_FAILURE";

export const FETCH_DISPLAYS_REQUEST = "FETCH_DISPLAYS_REQUEST";
export const FETCH_DISPLAYS_SUCCESS = "FETCH_DISPLAYS_SUCCESS";
export const FETCH_DISPLAYS_FAILURE = "FETCH_DISPLAYS_FAILURE";
